# Generated by Django 5.2.3 on 2025-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_author_blog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
